#ifndef _CONSTANTS_H_
#define _CONSTANTS_H_

#define BLOCK_SIZE 25

#define WIDTH 350
#define HEIGHT 700

#define WIDTH_IN_BLOCKS WIDTH/BLOCK_SIZE
#define HEIGHT_IN_BLOCKS HEIGHT/BLOCK_SIZE

#define NUMBER_OF_CHOICES 2

#endif 

